
version: '3.8'
services:
  app:
    stdin_open: true
    container_name: dev_workery_frontend
    restart: unless-stopped
    build:
        context: .
        dockerfile: dev.Dockerfile
        args:
          - REACT_APP_API_HOST=http://localhost:8000
          - REACT_APP_API_DOMAIN=localhost:8000
          - REACT_APP_API_PROTOCOL=http
          - REACT_APP_WWW_DOMAIN=localhost:3000
          - REACT_APP_WWW_PROTOCOL=http
          - REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_IN_BYTES=10485760
    ports:
        - '3000:3000'
    environment:
        CHOKIDAR_USEPOLLING: "true"
    volumes:
        - ./:/app

## Usage:
##   docker-compose -p dev_workery_frontend -f dev.docker-compose.yml up
##
## Go to in your browser:
##   http://localhost:1337/


# https://medium.com/@marvels0098/how-to-include-reactjs-app-in-docker-container-2e73068ce2d5
