# docker-compose -p workery_frontend -f prod.docker-compose.yml up
version: '3.8'
services:
  staticsite:
    stdin_open: true
    container_name: workery_frontend_app
    restart: unless-stopped
    build:
        context: .
        dockerfile: prod.Dockerfile
        args:
          - REACT_APP_API_HOST=http://theworkery.cloud
          - REACT_APP_API_DOMAIN=theworkery.cloud
          - REACT_APP_API_PROTOCOL=https
          - REACT_APP_WWW_DOMAIN=theworkery.app
          - REACT_APP_WWW_PROTOCOL=https
          - REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_IN_BYTES=10485760
    ports:
        - '3000:80'
