version: '3'

tasks:
  serve:
    cmds:
      - npm run start

  dev_start:
    cmds:
      - docker-compose -p dev_workery_frontend -f dev.docker-compose.yml up

  dev_end:
    cmds:
      - docker-compose -p dev_workery_frontend -f dev.docker-compose.yml down

  dev_console:
    cmds:
      - docker exec -it dev_workery_frontend bash

  start:
    cmds:
      - docker-compose up -d

  end:
    cmds:
      - docker-compose down

  console:
    cmds:
      - docker exec -it workery_frontend bash

  deploy:
    cmds:
      - docker build -f prod.Dockerfile -t over55/workery-frontend:latest --platform linux/amd64 --build-arg REACT_APP_API_HOST=https://theworkery.cloud --build-arg REACT_APP_API_DOMAIN=theworkery.cloud --build-arg REACT_APP_API_PROTOCOL=https --build-arg REACT_APP_WWW_DOMAIN=theworkery.app --build-arg REACT_APP_WWW_PROTOCOL=https --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_IN_BYTES=10485760 --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_ERROR_MESSAGE="File is too large. The maximum size is 10 MB." .
      - docker tag over55/workery-frontend:latest over55/workery-frontend:latest
      - docker push over55/workery-frontend:latest
