version: '3'

tasks:
  serve:
    cmds:
      - npm run start

  dev_start:
    cmds:
      - docker-compose -p dev_workery_frontend -f dev.docker-compose.yml up

  dev_end:
    cmds:
      - docker-compose -p dev_workery_frontend -f dev.docker-compose.yml down

  dev_console:
    cmds:
      - docker exec -it dev_workery_frontend bash

  start:
    cmds:
      - docker-compose up -d

  end:
    cmds:
      - docker-compose down

  console:
    cmds:
      - docker exec -it workery_frontend bash

  # The following command will build a docker image with the react production code for the `https://theworkery.app` domain and submit the image to docker hub.
  # This image can only be used by `Skills at Work / Over 55 (London) Inc.` organization.
  deploy:
    cmds:
      - docker build -f prod.Dockerfile -t over55/workery-frontend:prod-latest --platform linux/amd64 --build-arg REACT_APP_API_HOST=https://theworkery.cloud --build-arg REACT_APP_API_DOMAIN=theworkery.cloud --build-arg REACT_APP_API_PROTOCOL=https --build-arg REACT_APP_WWW_DOMAIN=theworkery.app --build-arg REACT_APP_WWW_PROTOCOL=https --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_IN_BYTES=10485760 --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_ERROR_MESSAGE="File is too large. The maximum size is 10 MB." --network=host --progress=plain .
      - docker tag over55/workery-frontend:prod-latest over55/workery-frontend:prod-latest
      - docker push over55/workery-frontend:prod-latest

  # The following command will build a docker image with the react production code the localhost domain and submit the image to docker hub.
  # This image can be used by the open-source community to run the frontend locally on their computer. The community image allows the frontend
  # to be accessed from the browsers `http://localhost:10001` address and connect to the backend address `http://localhost:10000`.
  deploy-selfhost:
    cmds:
      - docker build -f prod.Dockerfile -t over55/workery-frontend:selfhost-latest --platform linux/amd64 --build-arg REACT_APP_API_HOST=http://localhost:10000 --build-arg REACT_APP_API_DOMAIN=localhost:10000 --build-arg REACT_APP_API_PROTOCOL=http --build-arg REACT_APP_WWW_DOMAIN=localhost:10001 --build-arg REACT_APP_WWW_PROTOCOL=http --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_IN_BYTES=10485760 --build-arg REACT_APP_IMAGE_UPLOAD_MAX_FILESIZE_ERROR_MESSAGE="File is too large. The maximum size is 10 MB." .
      - docker tag over55/workery-frontend:selfhost-latest over55/workery-frontend:selfhost-latest
      - docker push over55/workery-frontend:selfhost-latest
